steps:
- name: node:10
  entrypoint: npm
  args: ['install']
- name: node:10
  entrypoint: npm
  args: ['run', 'build']
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./dist", "gs://petty-cash"]